### ISSUE TITLE
Errors for training custom dataset

### ISSUE THREAD

**Issue by Vilour** [WU-CVGL/BAD-Gaussians#7]
Hi, I tried to run with my custom data, and I had the following errors:

```
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.1341              
VanillaPipeline.get_train_loss_dict: 0.1025              
ImageRestorationTrainer.eval_iteration: 0.0000              
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/ubuntu/nerfstudio/nerfstudio/engine/trainer.py", line 250, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/ubuntu/nerfstudio/nerfstudio/utils/profiler.py", line 112, in inner
    out = func(*args, **kwargs)
  File "/home/ubuntu/nerfstudio/nerfstudio/engine/trainer.py", line 473, in train_iteration
    self.grad_scaler.scale(loss).backward()  # type: ignore
  File "/home/ubuntu/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/ubuntu/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
I also tried with the real_camera_motion_blur dataset and it works perfectly fine. What could be wrong?

**Comment by Vilour** [comment]
By the way, my .ply file for nerfstudio data is from depth camera, not from COLMAP. Is it necessary?

**Comment by LingzheZhao** [comment]
Hello, I would like to know what application you use to capture the data, is it [Polycam](https://docs.nerf.studio/quickstart/custom_dataset.html#polycam-capture) or [Record3D](https://docs.nerf.studio/quickstart/custom_dataset.html#record3d-capture)? Or if it's convenient for you, could you provide some sample data so I can test it directly?

**Comment by Vilour** [comment]
Thank you. Our data is from a custom device, which is more like a 3D scanner. However, the data is not suitable for public. May I have your email addresses? I could send to you privately.

**Comment by LingzheZhao** [comment]
Sure, you can send it to zhaolingzhe AT westlake.edu.cn, and I will check it when I'm free.

**Comment by LingzheZhao** [comment]
I see, can you try adding this parameter `--pipeline.datamanager.cache_images="cpu"`, e.g.

```sh
ns-train bad-gaussians \
    --data data/my_data/blurtanabata \
    --pipeline.datamanager.cache_images="cpu" \
    --vis viewer+tensorboard \
    nerfstudio-data --eval_mode "all"
```

(I set the default value to `"gpu"` [here](https://github.com/WU-CVGL/BAD-Gaussians/blob/bf6af1a9ab03ccdb602a4f0fbb6b27f69c14dca3/bad_gaussians/bad_config_method.py#L33) since otherwise it consumes nearly all CPU resources when I run two or more training instances on our 128-core server which is insane)

**Comment by Vilour** [comment]
Thank you! It works perfectly now!
